# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from interface.image_retrieval import InfoSearchTab, ImageRetrieval

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1356, 900)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.anomalyDetectionTab = QtWidgets.QWidget()
        self.anomalyDetectionTab.setObjectName("anomalyDetectionTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.anomalyDetectionTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.anomalyDetectionTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ADOriginImageContainer = QtWidgets.QGraphicsView(self.groupBox_6)
        self.ADOriginImageContainer.setObjectName("ADOriginImageContainer")
        self.verticalLayout_8.addWidget(self.ADOriginImageContainer)
        self.ADChoseImageBtn = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ADChoseImageBtn.setFont(font)
        self.ADChoseImageBtn.setObjectName("ADChoseImageBtn")
        self.verticalLayout_8.addWidget(self.ADChoseImageBtn)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.line_2 = QtWidgets.QFrame(self.anomalyDetectionTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ADBtn = QtWidgets.QPushButton(self.anomalyDetectionTab)
        self.ADBtn.setObjectName("ADBtn")
        self.horizontalLayout_6.addWidget(self.ADBtn)
        self.ADResetBtn = QtWidgets.QPushButton(self.anomalyDetectionTab)
        self.ADResetBtn.setObjectName("ADResetBtn")
        self.horizontalLayout_6.addWidget(self.ADResetBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_7 = QtWidgets.QGroupBox(self.anomalyDetectionTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ADResultContainer = QtWidgets.QGraphicsView(self.groupBox_7)
        self.ADResultContainer.setObjectName("ADResultContainer")
        self.verticalLayout_13.addWidget(self.ADResultContainer)
        self.verticalLayout_12.addWidget(self.groupBox_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 6)
        self.tabWidget.addTab(self.anomalyDetectionTab, "")
        self.segmentationTab = QtWidgets.QWidget()
        self.segmentationTab.setObjectName("segmentationTab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.segmentationTab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.segmentationTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SSOriginImageContainer = QtWidgets.QGraphicsView(self.groupBox_4)
        self.SSOriginImageContainer.setObjectName("SSOriginImageContainer")
        self.verticalLayout_7.addWidget(self.SSOriginImageContainer)
        self.SSChoseImageBtn = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SSChoseImageBtn.setFont(font)
        self.SSChoseImageBtn.setObjectName("SSChoseImageBtn")
        self.verticalLayout_7.addWidget(self.SSChoseImageBtn)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.line_3 = QtWidgets.QFrame(self.segmentationTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SSBtn = QtWidgets.QPushButton(self.segmentationTab)
        self.SSBtn.setObjectName("SSBtn")
        self.horizontalLayout_5.addWidget(self.SSBtn)
        self.SSResetBtn = QtWidgets.QPushButton(self.segmentationTab)
        self.SSResetBtn.setObjectName("SSResetBtn")
        self.horizontalLayout_5.addWidget(self.SSResetBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(0, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.segmentationTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.SSResultContainer = QtWidgets.QGraphicsView(self.groupBox_5)
        self.SSResultContainer.setObjectName("SSResultContainer")
        self.verticalLayout_10.addWidget(self.SSResultContainer)
        self.verticalLayout_14.addWidget(self.groupBox_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.horizontalLayout_8.setStretch(0, 4)
        self.horizontalLayout_8.setStretch(1, 6)
        self.tabWidget.addTab(self.segmentationTab, "")
        self.changeDetectionTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.changeDetectionTab.setFont(font)
        self.changeDetectionTab.setObjectName("changeDetectionTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.changeDetectionTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.changeDetectionTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CDOriginImageContainer1 = QtWidgets.QGraphicsView(self.groupBox)
        self.CDOriginImageContainer1.setObjectName("CDOriginImageContainer1")
        self.verticalLayout_6.addWidget(self.CDOriginImageContainer1)
        self.CDChoseImageBtn1 = QtWidgets.QPushButton(self.groupBox)
        self.CDChoseImageBtn1.setObjectName("CDChoseImageBtn1")
        self.verticalLayout_6.addWidget(self.CDChoseImageBtn1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.changeDetectionTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.CDOriginImageContainer2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.CDOriginImageContainer2.setObjectName("CDOriginImageContainer2")
        self.verticalLayout_16.addWidget(self.CDOriginImageContainer2)
        self.CDChoseImageBtn2 = QtWidgets.QPushButton(self.groupBox_2)
        self.CDChoseImageBtn2.setObjectName("CDChoseImageBtn2")
        self.verticalLayout_16.addWidget(self.CDChoseImageBtn2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(self.changeDetectionTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CDBtn = QtWidgets.QPushButton(self.changeDetectionTab)
        self.CDBtn.setObjectName("CDBtn")
        self.horizontalLayout_3.addWidget(self.CDBtn)
        self.CDResetBtn = QtWidgets.QPushButton(self.changeDetectionTab)
        self.CDResetBtn.setObjectName("CDResetBtn")
        self.horizontalLayout_3.addWidget(self.CDResetBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.changeDetectionTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.CDResultContainer = QtWidgets.QGraphicsView(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CDResultContainer.setFont(font)
        self.CDResultContainer.setObjectName("CDResultContainer")
        self.verticalLayout_15.addWidget(self.CDResultContainer)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_4.setStretch(1, 6)
        self.tabWidget.addTab(self.changeDetectionTab, "")
        
        # tab4
        self.removalTab = QtWidgets.QWidget()
        self.removalTab.setObjectName("removalTab")
        self.layoutWidget = QtWidgets.QWidget(self.removalTab)

        self.horizontalLayout_r1 = QtWidgets.QHBoxLayout(self.removalTab)
        self.horizontalLayout_r1.setObjectName("horizontalLayout_r1")

        self.layoutWidget.setGeometry(QtCore.QRect(11, 8, 531, 731))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_r1.addLayout(self.verticalLayout_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.removalOriginImageContainer = QtWidgets.QGraphicsView(self.groupBox_8)
        self.removalOriginImageContainer.setObjectName("removalOriginImageContainer")
        self.verticalLayout_9.addWidget(self.removalOriginImageContainer)
        self.removalChoseImageBtn = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.removalChoseImageBtn.setFont(font)
        self.removalChoseImageBtn.setObjectName("removalChoseImageBtn")
        self.verticalLayout_9.addWidget(self.removalChoseImageBtn)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.removalBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.removalBtn.setObjectName("removalBtn")
        self.horizontalLayout_9.addWidget(self.removalBtn)
        self.removalResetBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.removalResetBtn.setObjectName("removalResetBtn")
        self.horizontalLayout_9.addWidget(self.removalResetBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.setStretch(0, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.removalTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(541, 13, 781, 731))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_9 = QtWidgets.QGroupBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")

        self.removalResultContainer = QtWidgets.QGraphicsView(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.removalResultContainer.setFont(font)
        self.removalResultContainer.setObjectName("removalResultContainer")
        self.verticalLayout_18.addWidget(self.removalResultContainer)

        self.verticalLayout_17.addWidget(self.groupBox_9)
        self.horizontalLayout_r1.addLayout(self.verticalLayout_17)
        self.horizontalLayout_r1.setStretch(0, 4)
        self.horizontalLayout_r1.setStretch(1, 6)
        self.tabWidget.addTab(self.removalTab, "")
        # 菜单栏
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1356, 18))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menu_file.addAction(self.actionQuit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.tabWidget.setCurrentIndex(3)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.CDBtn.clicked.connect(MainWindow.changeDetection)
        self.CDChoseImageBtn2.clicked.connect(MainWindow.loadImage)
        self.CDResetBtn.clicked.connect(MainWindow.resetCDContainer)
        self.CDChoseImageBtn1.clicked.connect(MainWindow.loadImage)
        self.SSChoseImageBtn.clicked.connect(MainWindow.loadImage)
        self.removalChoseImageBtn.clicked.connect(MainWindow.loadImage)
        self.ADChoseImageBtn.clicked.connect(MainWindow.loadImage)
        self.SSBtn.clicked.connect(MainWindow.Segmentation)
        self.SSResetBtn.clicked.connect(MainWindow.resetSSContainer)
        self.ADBtn.clicked.connect(MainWindow.anomalyDetection)
        self.ADResetBtn.clicked.connect(MainWindow.resetADContainer)
        self.removalBtn.clicked.connect(MainWindow.Removal)
        self.removalResetBtn.clicked.connect(MainWindow.resetRemovalContainer)

        # vvlj: 添加新的tab
        self.add_tab4(MainWindow)
        ## vvlj: 添加新的tab
        self.infoSearchTab = InfoSearchTab()
        self.infoSearchTab.setupUi(self.tabWidget)
            # vvlj: 在此处添加按钮功能,可考虑放在InfoSearchTab内
        # self.infoSearchTab.set_click(MainWindow)
        self.image_retrieval = ImageRetrieval(MainWindow)
        self.infoSearchTab.pushButton.clicked.connect(self.image_retrieval.loadImage)
        self.infoSearchTab.pushButton_2.clicked.connect(self.image_retrieval.change_page)
        self.infoSearchTab.pushButton_3.clicked.connect(self.image_retrieval.change_page)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.horizontalLayout_10.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高分遥感图像处理系统"))
        self.groupBox_6.setTitle(_translate("MainWindow", "原图"))
        self.ADChoseImageBtn.setText(_translate("MainWindow", "选择图片"))
        self.ADBtn.setText(_translate("MainWindow", "异常检测"))
        self.ADResetBtn.setText(_translate("MainWindow", "重置"))
        self.groupBox_7.setTitle(_translate("MainWindow", "异常检测结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.anomalyDetectionTab), _translate("MainWindow", "异常检测"))
        self.groupBox_4.setTitle(_translate("MainWindow", "原图"))
        self.SSChoseImageBtn.setText(_translate("MainWindow", "选择图片"))
        self.SSBtn.setText(_translate("MainWindow", "语义分割"))
        self.SSResetBtn.setText(_translate("MainWindow", "重置"))
        self.groupBox_5.setTitle(_translate("MainWindow", "语义分割结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.segmentationTab), _translate("MainWindow", "语义分割"))
        self.groupBox.setTitle(_translate("MainWindow", "原图1"))
        self.CDChoseImageBtn1.setText(_translate("MainWindow", "选择图片"))
        self.groupBox_2.setTitle(_translate("MainWindow", "原图2"))
        self.CDChoseImageBtn2.setText(_translate("MainWindow", "选择图片"))
        self.CDBtn.setText(_translate("MainWindow", "变化检测"))
        self.CDResetBtn.setText(_translate("MainWindow", "重置"))
        self.groupBox_3.setTitle(_translate("MainWindow", "变化检测结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.changeDetectionTab), _translate("MainWindow", "变化检测"))
        self.groupBox_8.setTitle(_translate("MainWindow", "原图"))
        self.removalChoseImageBtn.setText(_translate("MainWindow", "选择图片"))
        self.removalBtn.setText(_translate("MainWindow", "去云雾"))
        self.removalResetBtn.setText(_translate("MainWindow", "重置"))
        self.groupBox_9.setTitle(_translate("MainWindow", "去云雾结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.removalTab), _translate("MainWindow", "去云雾"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))

    def add_tab4(self, MainWindow):
        '''
        :param MainWindow: 的
        :return:
        '''
        # 的
        self.removalTab1 = QtWidgets.QWidget()

        self.removalTab1.setObjectName("removalTab1")
        self.layoutWidget1 = QtWidgets.QWidget(self.removalTab1)

        self.horizontalLayout_r11 = QtWidgets.QHBoxLayout(self.removalTab1)
        self.horizontalLayout_r11.setObjectName("horizontalLayout_r11")

        self.layoutWidget1.setGeometry(QtCore.QRect(11, 8, 531, 731))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_2")
        self.horizontalLayout_r11.addLayout(self.verticalLayout_21)
        self.groupBox_81 = QtWidgets.QGroupBox(self.layoutWidget1)
        font1 = QtGui.QFont()
        font1.setPointSize(16)
        self.groupBox_81.setFont(font1)
        self.groupBox_81.setObjectName("groupBox_8")
        self.verticalLayout_91 = QtWidgets.QVBoxLayout(self.groupBox_81)
        self.verticalLayout_91.setObjectName("verticalLayout_9")
        self.removalOriginImageContainer1 = QtWidgets.QGraphicsView(self.groupBox_81)
        self.removalOriginImageContainer1.setObjectName("removalOriginImageContainer")
        self.verticalLayout_91.addWidget(self.removalOriginImageContainer1)
        self.removalChoseImageBtn1 = QtWidgets.QPushButton(self.groupBox_81)
        font1 = QtGui.QFont()
        font1.setPointSize(13)
        self.removalChoseImageBtn1.setFont(font1)
        self.removalChoseImageBtn1.setObjectName("removalChoseImageBtn")
        self.verticalLayout_91.addWidget(self.removalChoseImageBtn1)
        self.verticalLayout_21.addWidget(self.groupBox_81)
        self.line_41 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_4")
        self.verticalLayout_21.addWidget(self.line_41)
        self.horizontalLayout_91 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_91.setObjectName("horizontalLayout_91")
        self.removalBtn1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.removalBtn1.setObjectName("removalBtn")
        self.horizontalLayout_91.addWidget(self.removalBtn1)
        self.removalResetBtn1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.removalResetBtn1.setObjectName("removalResetBtn")
        self.horizontalLayout_91.addWidget(self.removalResetBtn1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_91)
        self.verticalLayout_21.setStretch(0, 1)
        self.layoutWidget_21 = QtWidgets.QWidget(self.removalTab1)
        self.layoutWidget_21.setGeometry(QtCore.QRect(541, 13, 781, 731))
        self.layoutWidget_21.setObjectName("layoutWidget_2")
        self.verticalLayout_171 = QtWidgets.QVBoxLayout(self.layoutWidget_21)
        self.verticalLayout_171.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_171.setObjectName("verticalLayout_17")
        self.groupBox_91 = QtWidgets.QGroupBox(self.layoutWidget_21)
        font1 = QtGui.QFont()
        font1.setPointSize(16)
        self.groupBox_91.setFont(font1)
        self.groupBox_91.setObjectName("groupBox_9")
        self.verticalLayout_181 = QtWidgets.QVBoxLayout(self.groupBox_91)
        self.verticalLayout_181.setObjectName("verticalLayout_18")

        self.removalResultContainer1 = QtWidgets.QGraphicsView(self.groupBox_91)
        font1 = QtGui.QFont()
        font1.setPointSize(16)
        self.removalResultContainer1.setFont(font1)
        self.removalResultContainer1.setObjectName("removalResultContainer")
        self.verticalLayout_181.addWidget(self.removalResultContainer1)

        self.verticalLayout_171.addWidget(self.groupBox_91)
        self.horizontalLayout_r11.addLayout(self.verticalLayout_171)
        self.horizontalLayout_r11.setStretch(0, 4)
        self.horizontalLayout_r11.setStretch(1, 6)
        self.tabWidget.addTab(self.removalTab1, "")

        # 设置文字
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_81.setTitle(_translate("MainWindow", "原图"))
        self.removalChoseImageBtn1.setText(_translate("MainWindow", "选择图片"))
        self.removalBtn1.setText(_translate("MainWindow", "地物分类"))
        self.removalResetBtn1.setText(_translate("MainWindow", "重置"))
        self.groupBox_91.setTitle(_translate("MainWindow", "地物分类结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.removalTab1), _translate("MainWindow", "地物分类"))

        # 按钮功能
        self.removalChoseImageBtn1.clicked.connect(MainWindow.loadImage)  # vvlj： 注意，此处需要联动改变MainWindow.loadImage
        self.removalBtn1.clicked.connect(MainWindow.feature_classification)
        self.removalResetBtn1.clicked.connect(MainWindow.resetRemovalContainer1)  # vvlj： 注意，此处需要添加MainWindow.resetRemovalContainer